const calendarURL="https://script.google.com/macros/s/AKfycbzduNdl_jQGJeXG9PKI8Ca_YiV4VXWA1uvAgA8POCcn-HsJuzj3Pe5N-vs2nTMwdh6P/exec";
const accountsURL="https://script.google.com/macros/s/AKfycbzS2FKvL6j_8mrQa-eR2Ze1I7xXeE_J7vvFLG2I5Evn6iIl5V238H4wvdvajxlefNyx/exec";
const whatsappNumber="201210425901";
document.getElementById("year").textContent=new Date().getFullYear();
window.addEventListener("scroll",()=>document.getElementById("navbar").classList.toggle("scrolled",scrollY>30));
function toggleMenu(){document.getElementById("navLinks").classList.toggle("open")}
document.querySelectorAll("nav a").forEach(a=>a.onclick=()=>document.getElementById("navLinks").classList.remove("open"));
const obs=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add("visible")),{threshold:.08});document.querySelectorAll(".reveal").forEach(x=>obs.observe(x));
function show(id){document.getElementById(id).classList.add("show");document.body.style.overflow="hidden"}function closeModal(id){document.getElementById(id).classList.remove("show");if(!document.querySelector(".modal.show"))document.body.style.overflow=""}
function openBooking(type=""){show("bookingModal");if(type){document.getElementById("eventType").value=type;updateFields()}}
function openCallModal(){show("callModal")}
function updateFields(){const t=document.getElementById("eventType").value;document.querySelectorAll(".conditional").forEach(x=>x.classList.remove("show"));if(t==="كتب كتاب في البيت"){timeField.classList.add("show");addressField.classList.add("show")}if(t==="خطوبة في البيت أو كافيه")addressField.classList.add("show");if(["سيشن زفاف و قاعة","سيشن خطوبة و قاعة","قاعة أو فرح"].includes(t))hallField.classList.add("show");if(t==="مناقشة ماجستير")uniField.classList.add("show")}
function latin(v){const a="٠١٢٣٤٥٦٧٨٩",e="۰۱۲۳۴۵۶۷۸۹";return String(v).replace(/[٠-٩]/g,x=>a.indexOf(x)).replace(/[۰-۹]/g,x=>e.indexOf(x))}
async function post(url,data){try{await fetch(url,{method:"POST",mode:"no-cors",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)})}catch(e){console.warn(e)}}
function submitBooking(e){e.preventDefault();const type=eventType.value,date=eventDate.value,name=fullName.value.trim(),phone=latin(document.getElementById("phone").value.trim()),homeTime=document.getElementById("homeTime").value,address=eventAddress.value.trim(),hallName=document.getElementById("hallName").value.trim(),university=document.getElementById("university").value.trim();if(!type||!date||!name||!phone){status.textContent="من فضلك كمّل البيانات المطلوبة.";return}if(type==="كتب كتاب في البيت"&&(!homeTime||!address)){status.textContent="من فضلك اكتب العنوان واختار الميعاد.";return}if(type==="خطوبة في البيت أو كافيه"&&!address){status.textContent="من فضلك اكتب العنوان.";return}if(["سيشن زفاف و قاعة","سيشن خطوبة و قاعة","قاعة أو فرح"].includes(type)&&!hallName){status.textContent="من فضلك اكتب اسم القاعة.";return}if(type==="مناقشة ماجستير"&&!university){status.textContent="من فضلك اكتب الجامعة.";return}const data={eventType:type,eventDate:date,homeTime,address,hallName,university,fullName:name,phone,source:"elmokadem-new-project"};status.textContent="جاري تجهيز الحجز...";post(calendarURL,data);post(accountsURL,data);const msg=["📸 *حجز جديد - المقدم فوتوغرافر*","",`الاسم: ${name}`,`الهاتف: ${phone}`,`المناسبة: ${type}`,`التاريخ: ${date}`,homeTime?`الميعاد: ${homeTime}`:"",address?`العنوان: ${address}`:"",hallName?`القاعة: ${hallName}`:"",university?`الجامعة: ${university}`:""].filter(Boolean).join("\n");status.textContent="تم تجهيز الحجز. سيتم فتح واتساب للتأكيد.";setTimeout(()=>window.open(`https://wa.me/${whatsappNumber}?text=${encodeURIComponent(msg)}`,"_blank"),400)}
const imgs=["assets/feedback/feedback-1.png","assets/feedback/feedback-2.jpeg","assets/feedback/feedback-3.png","assets/feedback/feedback-4.png","assets/feedback/feedback-5.png"];
function openFeedback(i){document.getElementById("feedbackImage").src=imgs[i-1];show("feedbackModal")}
let idx=0;const track=document.getElementById("reviewTrack"),cards=[...document.querySelectorAll(".track article")],dots=document.getElementById("reviewDots");cards.forEach((_,i)=>{const b=document.createElement("button");b.onclick=()=>go(i);if(!i)b.className="active";dots.appendChild(b)});function go(i){idx=(i+cards.length)%cards.length;track.style.transform=`translateX(${idx*(innerWidth<=900?100:50)}%)`;[...dots.children].forEach((x,j)=>x.classList.toggle("active",j===idx))}function changeReview(n){go(idx+n)}window.addEventListener("resize",()=>go(idx));
document.addEventListener("keydown",e=>{if(e.key==="Escape")document.querySelectorAll(".modal.show").forEach(m=>closeModal(m.id))});
const p=new URLSearchParams(location.search).get("package");if(p)addEventListener("load",()=>{openBooking(p);history.replaceState({},document.title,location.pathname)});
